# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9fcd98d619a824a09732e085dfbd7435555a07e6ad2099474b47463d373be4aff89b226811bad330a1a00bbb139df9adb8b89fd6564313689c6f62bd1c1d5c6

test:
  secret_key_base: a3b68a607b2d39b0574457daf1adb65d1b7940f1f82c8ca6dc11f43b387f0143247dba3a707b55ba464652093c77cd2b6e6e78ba90a09e881e4e49699482a3fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
